"use client";

import { type FormEvent, useEffect, useState } from "react";

import type { AddWatchlistItemInput } from "../types/watchlist";

import {
  DialogActions,
  FormError,
  FormField,
  inputClasses,
} from "./create-watchlist-dialog";

import { ModalShell } from "./modal-shell";

const AVAILABLE_STOCKS = [
  {
    symbol: "RELIANCE",
    name: "Reliance Industries Limited",
  },
  {
    symbol: "TCS",
    name: "Tata Consultancy Services",
  },
  {
    symbol: "INFY",
    name: "Infosys Limited",
  },
] as const;

interface AddStockDialogProps {
  isOpen: boolean;
  isSubmitting: boolean;
  existingSymbols: string[];
  onClose: () => void;
  onSubmit: (payload: AddWatchlistItemInput) => Promise<unknown>;
}

export function AddStockDialog({
  isOpen,
  isSubmitting,
  existingSymbols,
  onClose,
  onSubmit,
}: AddStockDialogProps) {
  const [symbol, setSymbol] = useState("");
  const [formError, setFormError] = useState<string | null>(null);

  const availableStocks = AVAILABLE_STOCKS.filter(
    (stock) => !existingSymbols.includes(stock.symbol),
  );

  useEffect(() => {
    if (isOpen) {
      setSymbol("");
      setFormError(null);
    }
  }, [isOpen]);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (!symbol) {
      setFormError("Select an equity to continue.");
      return;
    }

    try {
      setFormError(null);

      await onSubmit({
        symbol,
        exchange: "NSE",
      });

      onClose();
    } catch (error) {
      setFormError(
        error instanceof Error ? error.message : "Unable to add equity",
      );
    }
  }

  return (
    <ModalShell
      isOpen={isOpen}
      title="Add an equity"
      description="Add an NSE-listed company to the selected watchlist."
      onClose={onClose}
    >
      <form onSubmit={handleSubmit} className="space-y-5">
        <FormField label="Company" htmlFor="stock-symbol">
          <select
            id="stock-symbol"
            value={symbol}
            onChange={(event) => setSymbol(event.target.value)}
            className={inputClasses}
          >
            <option value="">Select a company</option>

            {availableStocks.map((stock) => (
              <option key={stock.symbol} value={stock.symbol}>
                {stock.symbol} — {stock.name}
              </option>
            ))}
          </select>
        </FormField>

        <div className="rounded-xl border border-cyan-400/15 bg-cyan-400/5 px-4 py-3">
          <p className="text-xs leading-5 text-cyan-100/70">
            Market prices are generated by the deterministic simulated market
            provider.
          </p>
        </div>

        {availableStocks.length === 0 && (
          <FormError message="All supported equities are already in this watchlist." />
        )}

        {formError && <FormError message={formError} />}

        <DialogActions
          submitLabel="Add equity"
          isSubmitting={isSubmitting || availableStocks.length === 0}
          onCancel={onClose}
        />
      </form>
    </ModalShell>
  );
}
